version: 1

input:
  root_dir: ./examples/medium
  files:
    - main.tf

output:
  mode: overwrite

options:
  workers: 2
  fail_on_no_change: false

edits:
  - type: search_replace
    old: e2-medium
    new: e2-standard-4

  - type: insert_hcl
    ensure_target_block: true
    guard:
      if_target_missing: true
    block:
      path: resource.google_container_node_pool.pool.node_config.shielded_instance_config
    hcl: |
      enable_secure_boot = true

  - type: set_attribute
    block:
      path: resource.google_container_node_pool.pool.node_config
    attribute: oauth_scopes
    value_hcl: '["https://www.googleapis.com/auth/cloud-platform"]'
    create_if_missing: true

  - type: delete_hcl
    block:
      path: resource.google_container_node_pool.pool
    attribute: tags
