version: 1

input:
  root_dir: ./examples/all-features
  files:
    - main.tf

output:
  mode: target_dir
  target_dir: ./examples/all-features/out/search-replace

options:
  workers: 1
  fail_on_no_change: false

edits:
  - type: search_replace
    old: legacy-project
    new: prod-project

  - type: search_replace
    old: legacy-logs-bucket
    new: prod-logs-bucket
